version: "3.2"
services:
    etc-backup:
        image: test/docker-restic

        build:
            dockerfile: Dockerfile
            context: .
            cache_from:
                - golang:1.11-alpine

        hostname: etc
        command: "restic-runner snapshots"
        volumes:
            - /etc:/data:ro
            - /etc/docker/etc:/root/.config
            - /etc/localtime:/etc/localtime:ro
        environment:
            - XDG_CACHE_HOME=/root/.config/cache
            - RCLONE_FAST_LIST=true
            - RCLONE_TRANSFERS=32
            - RCLONE_CHECKERS=16
            - RESTIC_CLEANUP=true
        network_mode: host

    etc-expire:
        image: test/docker-restic

        build:
            dockerfile: Dockerfile
            context: .

        hostname: etc
        command: "restic-runner expire"
        volumes:
            - /etc:/data:ro
            - /etc/docker/etc:/root/.config
            - /etc/localtime:/etc/localtime:ro
        environment:
            - XDG_CACHE_HOME=/root/.config/cache
            - RCLONE_FAST_LIST=true
            - RCLONE_TRANSFERS=32
            - RCLONE_CHECKERS=16
            - RESTIC_CLEANUP=true
        network_mode: host

    etc-snapshots:
        image: test/docker-restic

        build:
            dockerfile: Dockerfile
            context: .
            cache_from:
                - golang:1.11-alpine

        hostname: etc
        command: "restic-runner snapshots"
        volumes:
            - /etc:/data:ro
            - /etc/docker/etc:/root/.config
            - /etc/localtime:/etc/localtime:ro
        environment:
            - XDG_CACHE_HOME=/root/.config/cache
            - RCLONE_FAST_LIST=true
            - RCLONE_TRANSFERS=32
            - RCLONE_CHECKERS=16
            - RESTIC_CLEANUP=true
        network_mode: host

    home-backup:
        image: test/docker-restic

        build:
            dockerfile: Dockerfile
            context: .
            cache_from:
                - golang:1.11-alpine

        hostname: home
        command: "restic-runner backup"
        volumes:
            - /home/pkutzner:/data:ro
            - /etc/docker/pkutzner:/root/.config
            - /etc/localtime:/etc/localtime:ro
        environment:
            - XDG_CACHE_HOME=/root/.config/cache
            - RCLONE_FAST_LIST=true
            - RCLONE_TRANSFERS=32
            - RCLONE_CHECKERS=16
            - RESTIC_CLEANUP=true
        network_mode: host

    home-expire:
        image: test/docker-restic

        build:
            dockerfile: Dockerfile
            context: .
            cache_from:
                - golang:1.11-alpine

        hostname: home
        command: "restic-runner expire"
        volumes:
            - /home/pkutzner:/data:ro
            - /etc/docker/pkutzner:/root/.config
            - /etc/localtime:/etc/localtime:ro
        environment:
            - XDG_CACHE_HOME=/root/.config/cache
            - RCLONE_FAST_LIST=true
            - RCLONE_TRANSFERS=32
            - RCLONE_CHECKERS=16
            - RESTIC_CLEANUP=true
        network_mode: host

    home-snapshots:
        image: test/docker-restic

        build:
            dockerfile: Dockerfile
            context: .
            cache_from:
                - golang:1.11-alpine

        hostname: home
        command: "restic-runner snapshots"
        volumes:
            - /home/pkutzner:/data:ro
            - /etc/docker/pkutzner:/root/.config
            - /etc/localtime:/etc/localtime:ro
        environment:
            - XDG_CACHE_HOME=/root/.config/cache
            - RCLONE_FAST_LIST=true
            - RCLONE_TRANSFERS=32
            - RCLONE_CHECKERS=16
            - RESTIC_CLEANUP=true
        network_mode: host
